# Documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', '**/docs/**', '**/README*']

# Dependency updates
dependencies:
  - changed-files:
    - any-glob-to-any-file: ['**/pyproject.toml', '**/uv.lock', '**/requirements*.txt', '**/package.json', '**/yarn.lock', '**/Pipfile*']

# Bug fixes
bug:
  - changed-files:
    - any-glob-to-any-file: ['**/fix/**', '**/hotfix/**']

# New features
enhancement:
  - changed-files:
    - any-glob-to-any-file: ['**/feat/**', '**/feature/**']

