bug:
  - changed-files:
    - any-glob-to-any-file: ['**/bug/**', '**/fix/**', '**/*bug*', '**/*fix*']

enhancement:
  - changed-files:
    - any-glob-to-any-file: ['**/feat/**', '**/feature/**', '**/*feat*', '**/*feature*', '**/*enhancement*']

documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', '**/docs/**', '**/README*', '**/*doc*']

dependencies:
  - changed-files:
    - any-glob-to-any-file: ['**/pyproject.toml', '**/uv.lock', '**/requirements*.txt', '**/package.json', '**/yarn.lock', '**/Pipfile*']

tests:
  - changed-files:
    - any-glob-to-any-file: ['**/test/**', '**/tests/**', '**/*test*.py', '**/*_test.py', '**/test_*.py']

refactor:
  - changed-files:
    - any-glob-to-any-file: ['**/*refactor*']

ci:
  - changed-files:
    - any-glob-to-any-file: ['.github/**', '**/workflows/**', '**/.github/**', '**/ci/**']