# Documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', '**/docs/**', '**/README*']

# Dependency updates
dependencies:
  - changed-files:
    - any-glob-to-any-file: ['**/pyproject.toml', '**/uv.lock', '**/requirements*.txt', '**/package.json', '**/yarn.lock', '**/Pipfile*']

# Test files
tests:
  - changed-files:
    - any-glob-to-any-file: ['**/test/**', '**/tests/**', '**/test_*.py', '**/*_test.py']

# CI/CD workflows
ci:
  - changed-files:
    - any-glob-to-any-file: ['.github/**', '**/workflows/**']

# API related changes
api:
  - changed-files:
    - any-glob-to-any-file: ['**/api/**', '**/api_*.py', '**/*api*.py']

# Configuration files
config:
  - changed-files:
    - any-glob-to-any-file: ['**/*.toml', '**/*.yml', '**/*.yaml', '**/*.json', '**/*.ini', '**/*.cfg', '**/.env*']